-- 코드를 입력하세요
SELECT  DISTINCT  CAR_ID
FROM    CAR_RENTAL_COMPANY_CAR
INNER JOIN  CAR_RENTAL_COMPANY_RENTAL_HISTORY
USING   (CAR_ID)
WHERE   CAR_TYPE = '세단' AND START_DATE LIKE '____-10-__'
ORDER BY CAR_ID DESC